enhancement: API docs
crs4/rocrate-validator pull request #44
Opened 2024-11-25 15:51 UTC by kikkomep

This PR continues to address issue #40. It introduces and initializes the documentation, with a particular focus on the API classes designed for programmatic interaction with the validator.
A preview is available [here](https://mep-validator.readthedocs.io), while the official version will be accessible at https://rocrate-validator.readthedocs.io after the first release following the integration of this PR (the CI has already been extended and configured to support the automatic generation of the documentation).

2024-12-02 11:52 UTC, simleo commented
Links like `[CLI-based validation](#cli-based-validation)` work only in the rendering of the Markdown file, not when included in the Sphinx-generated docs.

2024-12-03 10:35 UTC, simleo commented on rocrate_validator/models.py
> +        :rtype: :py:class:rdflib.Graph
`:py:class:rdflib.Graph` is not rendered

2024-12-03 10:35 UTC, simleo commented on rocrate_validator/models.py
> +            value(Optional[str]): The value of the result path which caused the issue(if any)
These parameters are not rendered

2024-12-04 18:12 UTC, kikkomep commented on docs/img/core-model.png
`C`  $->$ `Class`
`A` $->$ `Abstract Class`

2024-12-04 18:14 UTC, kikkomep commented on rocrate_validator/services.py
> +    :param allow_requirement_check_override: the requirement check override flag
Param description updated in https://github.com/crs4/rocrate-validator/pull/44/commits/55df401f0f42dcc7206b01badfc686fb648727c2

2024-12-04 18:14 UTC, kikkomep commented on rocrate_validator/services.py
> +    :param allow_requirement_check_override: the requirement check override flag
Param description updated in https://github.com/crs4/rocrate-validator/pull/44/commits/55df401f0f42dcc7206b01badfc686fb648727c2

2024-12-04 18:17 UTC, kikkomep commented on rocrate_validator/models.py
>      rocrate_uri: URI
[fixed](https://mep-validator.readthedocs.io/en/latest/10_api/#rocrate_validator.models.ValidationSettings.rocrate_uri)

2024-12-04 18:20 UTC, kikkomep commented on rocrate_validator/models.py
> +            value(Optional[str]): The value of the result path which caused the issue(if any)
the parameters have been renamed and their description is now [rendered](https://mep-validator.readthedocs.io/en/latest/10_api/#rocrate_validator.models.CheckIssue.violatingEntity)

2024-12-05 09:01 UTC, ilveroluca requested changes

2024-12-05 09:01 UTC, ilveroluca commented on docs/10_api.rst
> +    :file: ./diagrams/core-services.validate.svg
Add a minimal caption. E.g.,

> UML class diagram of main validation components.
Legend: "C" -> class; "A" -> abstract class; "I" -> interface. Arrow: the source object acts on the destination object.

Also, being a Python module, `services` may be better described as a "struct", rather than an "interface".

2024-12-09 14:14 UTC, kikkomep commented on docs/diagrams/core-services.profiles.plantuml
> +    services ..> rocrate_validator.models.Severity : " filters"
fixed in https://github.com/crs4/rocrate-validator/pull/44/commits/7e85cc36d68bd9f551334d65f4e22c3017cd5f09

2024-12-09 14:21 UTC, kikkomep commented on docs/10_api.rst
> +    :file: ./diagrams/core-services.validate.svg
> Add a minimal caption. E.g.,
> 
> > UML class diagram of main validation components.
> > Legend: "C" -> class; "A" -> abstract class; "I" -> interface. Arrow: the source object acts on the destination object.
 
caption added in https://github.com/crs4/rocrate-validator/pull/44/commits/dee45c134ec226c13bb7b91223a080de4a26efa4

2024-12-09 14:26 UTC, kikkomep commented on docs/10_api.rst
> +    :file: ./diagrams/core-services.validate.svg
> Also, being a Python module, `services` may be better described as a "struct", rather than an "interface".

I think an **Interface** is the most appropriate choice to represent a Python module with public service functions because it defines a contract of accessible methods, similar to how public functions in a module are used. Unlike a **struct**, which mainly represents data, an Interface emphasizes the available functionality, making it well-suited for illustrating a module’s public API.

2024-12-10 11:58 UTC, merged