docs: add "how it works" section
crs4/rocrate-validator pull request #57
Opened 2024-12-12 17:27 UTC by kikkomep

a live preview is available [here](https://mep-validator.readthedocs.io/en/docs-how-it-works/4_how_it_works/)

2024-12-12 18:44 UTC, ilveroluca commented on docs/4_how_it_works.rst
> +      - **Non-Interactive Mode:** the system will use all candidate profiles
still unclear

2024-12-13 14:03 UTC, simleo requested changes

2024-12-13 14:03 UTC, simleo commented on docs/4_how_it_works.rst
> +      - **Non-Interactive Mode:** the system will use all candidate profiles
```suggestion
      - in **Non-Interactive Mode:** the system will use all candidate profiles
```

2024-12-16 16:35 UTC, kikkomep commented on docs/4_how_it_works.rst
> +Workflow Testing RO-Crate, which extends Workflow RO-Crate.
fixed in https://github.com/crs4/rocrate-validator/pull/57/commits/ec6efe2d8e6b07704f6e600e833d8c3e2e0c7f95

2024-12-16 16:35 UTC, kikkomep commented on docs/4_how_it_works.rst
> +    - If no precise match is found, the system will:
fixed in https://github.com/crs4/rocrate-validator/pull/57/commits/ec6efe2d8e6b07704f6e600e833d8c3e2e0c7f95

2024-12-16 16:35 UTC, kikkomep commented on docs/4_how_it_works.rst
> +      - **Non-Interactive Mode:** the system will use all candidate profiles
fixed in https://github.com/crs4/rocrate-validator/pull/57/commits/ec6efe2d8e6b07704f6e600e833d8c3e2e0c7f95

2025-02-06 08:44 UTC, simleo approved these changes

2025-02-06 09:04 UTC, merged